name: FTP Deploy

on:
  push:
    branches:
      - main  # or your deploy branch

jobs:
  ftp-deploy:
    name: Upload via FTP
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3
      
    - name: Install lftp
      run: sudo apt-get update && sudo apt-get install -y lftp
 
    - name: FTP Deploy
      env:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: ${{ secrets.FTP_TARGET }}/
        exclude: |
            **/.git*
            **/.github*
            **/README.md
            **/SQL
            **/.env
            **/tests/**
            admin/includes/dbconnection.php
            user/includes/dbconnection.php
            employee/includes/dbconnection.php
        run: |
          lftp -c "
          open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER
          mirror -R --delete --verbose ./ $FTP_TARGET
          "
        verbose: true
