name: Lint & Test PHP (Staging)

on:
  push:
    branches: [ feature/patient-report-workflow ]
  pull_request:
    branches: [ feature/patient-report-workflow ]

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install PHP_CodeSniffer
        run: composer global require squizlabs/php_codesniffer

      - name: Add composer bin to path
        run: echo "$HOME/.composer/vendor/bin" >> $GITHUB_PATH

      - name: Run phpcbf to auto-fix only .php files
        run: |
            phpcs -d memory_limit=2G --standard=PSR12 \
            --ignore=vendor/*,js/*,css/*,fonts/*,images/*,admin/assets/*,user/assets/*,employee/assets/* --extensions=php . | tee phpcs.log

      - name: Run phpcs
        run: |
          phpcs -d memory_limit=1G --standard=PSR12 \
          --ignore=vendor/*,js/*,css/*,fonts/*,images/*,admin/assets/*,user/assets/*,employee/assets/* --extensions=php . | tee phpcs.log
